version: 0.2

phases:
  install:
    commands:
      - curl -fsSL https://dev.nodesource.com/setup_16.x | sudo -E bash -
      - yum install gcc-c++ make
  pre_build:
    commands:
      - npm i -g @angular/cli
      - npm install --force
  build:
    commands:
      - ng build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/app-name-ng
